# Generated by Django 5.1.7 on 2025-03-17 19:24

from __future__ import annotations

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("Long/Short Equity", "Long/Short Equity"),
                            ("Global Macro", "Global Macro"),
                            ("Arbitrage", "Arbitrage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("aum", models.IntegerField(blank=True, null=True)),
                ("inception_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        models.F("strategy"), models.F("name"), name="ix_fund_strategy"
                    )
                ]
            },
        )
    ]
